Support/Controllers/ReplyController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Protocol.Plugins;
using Support.Data;
using Support.Models;
using Support.Models.ViewModels;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Support.EmailDependencies;
using Microsoft.Graph;

namespace Support.Controllers
{
    public class ReplyController : Controller
    {
        private readonly ApplicationDbContext _context;
        public static List<Ticket> ticketSelected;
        public static List<Models.Chat> ticketChat;
        private readonly GraphServiceClient _graphServiceClient;




        public ReplyController(ApplicationDbContext context, GraphServiceClient graphServiceClient)
        {
            _context = context;
            _graphServiceClient = graphServiceClient;
        }

        public async Task<IActionResult> DisplaySupportEmpTickets()
        {
            var users = await _graphServiceClient.Me.Request().GetAsync();

            if (users.JobTitle== "Support Lead") 
            {
               
                return RedirectToAction( "DisplayTickets", "Ticket");
            }
            if (users.JobTitle == "Lecturer") 
            {
                var empId = users.Id;
                var specificEmp = _context.SupportEmployees.Include(tickets => tickets.AssignedTickets).Where(supportEmp => supportEmp.Id == empId).FirstOrDefault();
                return View(specificEmp); 
            }


            return RedirectToAction("AccessDenied");
        }
        public async Task<IActionResult> AccessDenied()
        {
            return View();
        }
        public async Task<IActionResult> CloseTicket(int ticketId)
        {
            var foundTicket = _context.Tickets.FirstOrDefault(ticket => ticket.Id == ticketId);
            foundTicket.Status = TicketStatus.Closed;
            _context.SaveChanges();
          
            return RedirectToAction("DisplayTicketChat");

        }
            [HttpGet]
        public async Task<IActionResult> FindTicketChat(int Id)
        {
            ticketSelected = await _context.Tickets.Include(ticket => ticket.Attachments).Where(x => x.Id == Id).ToListAsync();
            ticketChat = await _context.Chats.Include(x => x.Responses).Where(ticket => ticket.TicketId == Id).ToListAsync();
            
            return RedirectToAction("DisplayTicketChat");
        }

       
            public async Task<IActionResult> DisplayTicketChat()
        {
            /*//get all tickets that are unassigned
            var ticketSelected = await _context.Tickets.Include(ticket => ticket.Attachments).Where(x => x.Id == Id).ToListAsync();
            //get all support members
            var ticketChat = await _context.Chats.Include(x => x.Responses).Where(ticket => ticket.TicketId == Id).ToListAsync();

*/
            
            var viewModel = new ChatViewModel
            {
                ticket = ticketSelected,
                chat = ticketChat
            };

           

                return View(viewModel);
    
        }

        public async Task<IActionResult> SendReply(int id, string recipient, string body, string subject)
        {
            var emp = await _graphServiceClient.Me.Request().GetAsync();


            var specificEmp = await _context.SupportEmployees.Include(tickets => tickets.AssignedTickets).Include(chats=>chats.Chats).Where(supportEmp => supportEmp.Id == emp.Id).FirstOrDefaultAsync();

            Emailer email = new Emailer();
            email.sendEmail(emp.Mail, recipient, subject, body, specificEmp.Password);

            var response = new TicketResponse
            {

                Subject = subject,
                Body = body,
                EmailSender = specificEmp.Email,
                EmailRecipient = recipient,
                TicketId = id
            };

            if (IfChatIsNull(id))
            {
                var chat = new Models.Chat { UserEmail = recipient, TicketId = id, Responses = new List<TicketResponse>() };
                _context.Chats.Add(chat);
                _context.SaveChanges();
            }
            else {
                var item = _context.Chats.Include(response => response.Responses).Where(chat => chat.TicketId == id).FirstOrDefault();
                item.Responses.Add(response);
                _context.SaveChanges();

            }
            
                



            ticketSelected = await _context.Tickets.Include(ticket => ticket.Attachments).Where(x => x.Id == id).ToListAsync();
            ticketChat = await _context.Chats.Include(x => x.Responses).Where(ticket => ticket.TicketId == id).ToListAsync();
            
            return RedirectToAction("DisplayTicketChat");
        }


        public bool IfChatIsNull(int id) 
        {
           
            var tcktChat = _context.Chats.Where(ticketChat => ticketChat.TicketId == id).ToList();

            if (tcktChat.Count==0)
            {return true;}

            else 
            { return false; }

            }

    }
}

Support/Views/Reply/AccessDenied.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
        }

        .container {
            background-color: #fff;
            border-radius: 10px;
            padding: 20px;
            margin: 100px auto;
            max-width: 400px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #e74c3c;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Access Denied</h1>
        <p>We're sorry, but you do not have permission to access this page.</p>
        <p>Please contact the administrator for further assistance.</p>
    </div>
</body>
</html>

Support/Views/Reply/DisplaySupportEmpTickets.cshtml
@model Support.Models.SupportEmployee

<table class="table table-hover">
    <thead>
        <tr>
            <th style="font-weight: 600;" scope="col">sender</th>
            <th style="font-weight: 600;" scope="col">subject</th>
            <th style="font-weight: 400;color: rgba(0, 0, 0, 0.60);" scope="col">content</th>
            <th style="font-weight: 600;" scope="col">Date submited</th>
        </tr>
    </thead>
    <tbody> 
        

        @foreach(var ticket in Model.AssignedTickets)
        {
            
                <form asp-action="CloseTicket">
               <input type="hidden" name="ticketId" value="@ticket.Id" />
               
                <tr class="clickable-row" onclick="location.href = '@Url.ActionLink("FindTicketChat", "Reply", new { Id=ticket.Id })'">
                <td>@ticket.UserEmail</td>
                <td>@ticket.Subject</td>
                <td class="column">@ticket.Body</td>
                <td>@ticket.TimeStamp</td>

                </tr>
               @* <button type="submit" class="btn btn-outline-danger">Close</button>*@
           </form>
          
            
        }  
    </tbody>
</table>

            <style>

                table {
            table-layout:fixed;
            width: 150px;
        }


    .clickable-row {
        cursor: pointer;
    }

    .column{
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    th:nth-child(1) {
        width: 15%; /* Adjust the width for the first column */
    }

    th:nth-child(2) {
        width: 20%; /* Adjust the width for the second column */
    }

    th:nth-child(3) {
        width: 45%; /* Adjust the width for the second column */
    }

    th:nth-child(4) {
        width: 20%; /* Adjust the width for the fourth column */
    }

</style>

Support/Views/Reply/DisplayTicketChat.cshtml
@model Support.Models.ViewModels.ChatViewModel

<div>
  
    <div class="support-employee-statistics-container">
       
            <div class="initial-ticket">
            <img src="@Url.Content("/images/user-circle-svgrepo-com.svg")" alt="" class="img" />
            @foreach (var ticket in Model.ticket)
            {
            <div class="ticket-subject">@ticket.Subject</div>
            <div class="ticket-priority">@ticket.TicketPriority</div>
            <div class="ticket-email">@ticket.UserEmail</div>
            <div class="ticket-body">
                 <span>@ticket.Body</span>
            </div>
            <div class="ticket-date">
                 <span>@ticket.TimeStamp</span>
            </div>
            
            }
            </div>



        @foreach (var reply in Model.chat)
        {
            <div class="chats-container">
                @foreach (var response in reply.Responses)
                {
                    <div class="card container2">
                        <div class="card-body">
                            <h4 class="response-email">@response.EmailSender</h4>
                            <p class="response-body">@response.Body</p>
                        </div>
                        <div class="response-time-date">
                            <p>2023/10/05 15:31:55</p>
                        </div>
                    </div>
                }


            </div>                  
        } 
        <br/>
        <button id="openModalBtn">reply</button>

            <div id="emailModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <div class="model-header">
                    <h2>Compose Email
                        <span class="close" id="closeModalBtn">×</span>
                    </h2>   
                    
            </div>


                <form asp-action="SendReply">
                    @foreach (var ticket in Model.ticket)
                    {
                        <input type="hidden" name="id" value="@ticket.Id" />
                        
                  
                        <div class="recipient">
                        <label for="recipient">Recipient:</label>
                        <input type="text" id="recipient" name="recipient" placeholder="@ticket.UserEmail" value="@ticket.UserEmail" readonly>
                        </div>
                    }
                    <br />
                
                    <div class="subject">
                        <label for="subject">Subject:</label>
                        <input type="text" id="subject" name="subject" placeholder="Enter subject"><br>
                    </div>
                    <br />
               
                    <div class="message">
                        <label for="message">Message:</label>
                        <textarea id="body" name="body" rows="5" placeholder="Compose your email"></textarea><br>
                    </div>
                    <br />
                

                <input type="submit" value="Send Email">
            </form>
        </div>
    </div>
          
  </div>





</div>
   

<style>
    .support-employee-statistics-container {
    width: 100%;
    display: flex;
    overflow: auto;
    min-height: 100vh;
    align-items: flex-end;
    flex-direction: column;
    justify-content: flex-end;
}

    .initial-ticket
    {
    top: 69px;
    right: -3px;
    width: 100%;
    position:absolute;
    box-shadow: 0px 0px 10px 0px #d4d4d4;
    overflow: hidden;
    margin-bottom: 25px;
    }

    .ticket-subject
    {
       
        top: 7%;
        left: 3%;
        max-width: 26cm;
        position: relative;
        font-size: 34px;
        font-style: normal;
        font-weight: 300;
       
    }

    .ticket-priority
    {
       
        top: -50px;
        left: 90%;
        max-width:3.5cm;
        
        position: relative;
        font-size: 25px;
        font-style: normal;
        font-weight: 200;
    }

    .ticket-email 
    {
        
        top: 45%;
        left: 10%;
        max-width: 15cm;
        position: relative;
        font-size: 20px;
        font-style: normal;
        font-weight: 600;
    }

    .ticket-body {
        
        float:left;
        top: 65%;
        left: 10%;
        position: relative;
        font-size: 15px;
        max-width: 20cm;
    }

    .ticket-date 
    {
       
        top: 75%;
        left: 90%;
        max-width: 120px;
        position: relative;
        font-size: 10px;
    }
    
    .container2 {
        margin-bottom:8px;
        box-shadow: 0px 0px 10px 0px #d4d4d4;
        width:45cm;        
    }

    .img{
        width: 2cm;
        height: 3cm;
        top: 70px;
        left: 20px;
        position: absolute;
    }

    .chats-container{
        top: 45%;
        left: -3px;
        position: absolute;
        margin-bottom:10px;
    }

    .response-email {
        max-width: 15cm;
        font-size: 20px;
        font-style: normal;
        font-weight: 600;
    }

    .response-body{
        font-size: 15px;
        max-width: 20cm;
    }

    .response-time-date {
        font-size: 10px;
        right: 25%;
        bottom: 8%;
        position: absolute;
        max-width: 120px;
    }

   .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgba(0, 0, 0, 0.4); /* Black with a little bit of transparency */
}

/* Style for the modal content */
.modal-content {
    background-color: #fefefe;
    margin: 15% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 70%; /* Could be adjusted to your liking */
}

/* Close button style */
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover {
    color: black;
    text-decoration: none;
    cursor: pointer;
}

.recipient {
        

}

.subject {
        
}

.message {
       
}

    .modal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
        background-color: #f0f0f0;
        border-bottom: 1px solid #ccc;
    }
</style>


<script>
    // Get the modal and button elements
    var modal = document.getElementById('emailModal');
    var openModalBtn = document.getElementById('openModalBtn');
    var closeModalBtn = document.getElementById('closeModalBtn');

    // When the user clicks the button, open the modal
    openModalBtn.onclick = function () {
        modal.style.display = "block";
    }

    // When the user clicks on the close button, close the modal
    closeModalBtn.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>