Support/Controllers/SupportEmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Graph;
using Support.Data;
using Support.Models;
namespace Support.Controllers
{
    public class SupportEmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly GraphServiceClient _graphServiceClient;



        public SupportEmployeesController(ApplicationDbContext context, GraphServiceClient graphServiceClient)
        {
            _context = context;
            _graphServiceClient = graphServiceClient;
        }

        public async Task<IActionResult> DisplayAllSupportEmployees()
        {

            var allSupportEmp = await _context.SupportEmployees.ToListAsync();
            


            return View(allSupportEmp);
        }

        public async Task<IActionResult> SupportEmployeeStatistics(string supportId)
        {
            var supportEmpStats = await _context.SupportEmployees.Include(ticket=>ticket.AssignedTickets).Where(emp=>emp.Id==supportId).FirstOrDefaultAsync();
         

            return View(supportEmpStats);
        }
    }
}

Support/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    @using System.Security.Principal
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Support</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Support.styles.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/css/displayTicket.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Support</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewBag.SomeProperty == "Hello")
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SupportEmployees" asp-action="DisplayAllSupportEmployees">profiles</a>
                            </li>
                        }
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Support - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>